### ISSUE TITLE
Wrong end mark.

### ISSUE THREAD

**Issue by MegaV0lt** [kfb77/vdr-plugin-markad#15] opened 2024-07-23 08:00 UTC
recording has wrong end mark. See Log:

```
root@vdr01:/video/The_Good_Neighbor_-_Das_Böse_wohnt_nebenan/2024-07-22.22.10.2-0.rec# cat markad.log
Mon Jul 22 22:10:01 [6756] INFO:  starting markad v4.0.2 (64bit)
Mon Jul 22 22:10:01 [6756] INFO:  on /mnt/data/video/The_Good_Neighbor_-_Das_Böse_wohnt_nebenan/2024-07-22.22.10.2-0.rec
Mon Jul 22 22:10:11 [6756] INFO:  no logo for ZDF_HD 16:9 found in logo cache directory /tmp, trying to find logo in recording directory
Mon Jul 22 22:10:11 [6756] INFO:  no logo for ZDF_HD 16:9 found in recording directory /mnt/data/video/The_Good_Neighbor_-_Das_Böse_wohnt_nebenan/2024-07-22.22.10.2-0.rec, trying to extract logo from recording
Mon Jul 22 22:10:12 [6756] INFO:  use hardware acceleration for stream 0
Mon Jul 22 22:18:52 [6756] INFO:  pre-timer:         0:05:00h
Mon Jul 22 22:18:52 [6756] INFO:  broadcast length:  1:35:00h
Mon Jul 22 22:18:52 [6756] INFO:  channel: ZDF_HD
Mon Jul 22 22:18:52 [6756] INFO:  use hardware acceleration for stream 0
Mon Jul 22 22:18:52 [6756] ERROR: cIndex::GetTimeFromFrame(): frame index not initialized
Mon Jul 22 22:18:52 [6756] ERROR: cMarks::IndexToHMSF(): failed to get time from frame (-1)
Mon Jul 22 22:18:52 [6756] ERROR: cMarks::Save(): failed to get PTS timestamp for (-1)
Mon Jul 22 22:18:52 [6756] INFO:  logo ZDF_HD-A16_9 not found
Mon Jul 22 22:18:53 [6756] INFO:  use hardware acceleration for stream 0
Mon Jul 22 22:20:25 [6756] INFO:  no valid logo found for ZDF_HD 16:9, disable logo detection
Mon Jul 22 22:20:28 [6756] INFO:  audio channel change from 2 to 6 (17763)* at 0:05:55.26
Mon Jul 22 22:20:28 [6756] INFO:  start horiz. borders (17763)* at 0:05:55.26
Mon Jul 22 22:22:48 [6756] INFO:  HD video with aspect ratio of 16:9 detected
Mon Jul 22 22:22:48 [6756] INFO:  using channel start mark on position (17763) at 0:05:55.26 as broadcast start
Mon Jul 22 22:46:59 [6756] INFO:  use hardware acceleration for stream 0
Mon Jul 22 23:23:58 [6756] INFO:  use hardware acceleration for stream 0
Mon Jul 22 23:24:13 [6756] ERROR: end of recording before recording length from VDR info file reached
Mon Jul 22 23:24:13 [6756] INFO:  end   assumed (221851)  at 1:13:57.08
Mon Jul 22 23:24:13 [6756] INFO:  duration:                    time   701s -> 0:11:41h
```
Infos from VDR/skin flatPlus:
![rec](https://github.com/user-attachments/assets/2dd1f793-bbe7-4be9-9b79-f3ac26388edf)

**Comment by kfb77** [comment] 2024-07-23 10:15
Please run markad as described [here](https://github.com/kfb77/vdr-plugin-markad/wiki#support) and post the files.

**Comment by MegaV0lt** [comment] 2024-07-23 12:05
Took a while...
[markad-files.zip](https://github.com/user-attachments/files/16348463/markad-files.zip)

**Comment by MegaV0lt** [comment] 2024-07-23 12:08
Now start mark is also wrong 
![Auswahl_312](https://github.com/user-attachments/assets/86f7cb40-723f-43be-9955-899e3172c4a4)

**Comment by kfb77** [comment] 2024-07-23 12:42
I see no bug, but ways to avoid something like this in the future:
1. Timer Start was 22:15:00, recording start was 22:15:57. Have you started it manually ? Anyway, this is a incomplete recording start and I can not determine the broadcast start, I have to use the recording start.
2. The real broadcast start was 05:55min after recording start. Even with recording start in time such delay can give wrong start marks. To solve this problem, turn on VPS in your markad plugin configuration and I can use the VPS start event to recognize the delayed broadcast start. This will only work with ÖR, but in this case it will solve the problem.
3. Wrong stop mark is a follow-up error from (2). Assumed end time is timer start + length. If start is wrong assumed end will be wrong. But I have no end mark at all. Was the next broadcast also with border and with 6 channel ?

**Comment by MegaV0lt** [comment] 2024-07-23 14:02
1. No it was started by a vdr timer that was set manualy some day before by selecting an epg entry
2. I think it is the pre time every timer gets. Is set  to 5 or 7 minutes in case the program starts earlyer. Also a afterrun of 15 mins is set to the timer in case the program is delayed. Setting of vdr or epgsearch 
3. No idea what changed. But with markad preor to version 4 it was almost perfect in detecting marks, I have no idea what comes next to the program. havent watched it.

ps: i hav markad running during the recording, because i sometime watch during recording and i want marks then...
pps: I have hwaccel on to reduce cpu load

**Comment by MegaV0lt** [comment] 2024-07-23 14:04
addition to 1:
```
root@vdr01:/video/The_Good_Neighbor_-_Das_Böse_wohnt_nebenan/2024-07-22.22.10.2-0.rec# cat markad.log
Mon Jul 22 22:10:01 [6756] INFO:  starting markad v4.0.2 (64bit)
Mon Jul 22 22:10:01 [6756] INFO:  on /mnt/data/video/The_Good_Neighbor_-_Das_Böse_wohnt_nebenan/2024-07-22.22.10.2-0.rec
```

**Comment by MegaV0lt** [comment] 2024-07-23 14:12
Also this is wrong:
```
Mon Jul 22 23:24:13 [6756] ERROR: end of recording before recording length from VDR info file reached
Mon Jul 22 23:24:13 [6756] INFO:  end   assumed (221851)  at 1:13:57.08
```
Recording length is 1:59:00

**Comment by kfb77** [comment] 2024-07-23 14:23
1. This is strange. The creation time of the recording folder is 22:15:57, the markad log in this folder starts 22:10:01 ???
Please show "ls -l /mnt/data/video/The_Good_Neighbor*"
- Which file system is this ?
- Is your system time correct ?
2. This is strange too. The error is not in the newer created logo file. How was markad started ? From the short log file I assume "during recording". I will try to reproduce this, I never use markad in this this way.

**Comment by kfb77** [comment] 2024-07-23 14:30
The loglevel 2 don't tell much about bugs. Please switch to extended loging (and accept temporary some big log files). Maybe there is a problem with hwaccel on your system. I can only test vappi, which do you use ?
Please repeat markad on this recording with additional parameter --hwaccel=<what you used> and post markad.log

**Comment by MegaV0lt** [comment] 2024-07-23 14:35
1. have moved the recording to ext hd in the meantime to watch it out of house
```
root@vdr01:~# ls -l /media/vdr/Seagate/video/The_Good_Neighbor_-_Das_Böse_wohnt_nebenan/
insgesamt 128
drwxr-xr-x 2 vdr vdr 131072 Jul 23 13:59 2024-07-22.22.10.2-0.rec
```
Full dir:
```
root@vdr01:~# ls -l /media/vdr/Seagate/video/The_Good_Neighbor_-_Das_Böse_wohnt_nebenan/2024-07-22.22.10.2-0.rec/
insgesamt 13226624
-rwxr-xr-x 1 vdr vdr 4194975788 Jul 22 22:46 00001.ts
-rwxr-xr-x 1 vdr vdr 4194888556 Jul 22 23:23 00002.ts
-rwxr-xr-x 1 vdr vdr 4194530040 Jul 23 00:00 00003.ts
-rwxr-xr-x 1 vdr vdr  953524532 Jul 23 00:09 00004.ts
-rwxr-xr-x 1 vdr vdr     690414 Jul 22 22:14 fanart.jpg
-rwxr-xr-x 1 vdr vdr    2856008 Jul 23 00:09 index
-rwxr-xr-x 1 vdr vdr       1667 Jul 22 22:15 info
-rwxr-xr-x 1 vdr vdr       1065 Jul 22 22:12 info.epg2vdr
-rwxr-xr-x 1 vdr vdr     135484 Jul 23 13:54 markad.log
-rwxr-xr-x 1 vdr vdr         12 Jul 22 22:10 markad.vps
-rwxr-xr-x 1 vdr vdr        126 Jul 23 13:54 marks
-rwxr-xr-x 1 vdr vdr    1115390 Jul 22 22:14 poster.jpg
-rwxr-xr-x 1 vdr vdr          9 Jul 23 14:08 resume
-rwxr-xr-x 1 vdr vdr        243 Jul 22 22:14 tvscraper.json
```
You can see that markad.vps was created 22:20 and the "end" at index: 00:09

Filesystem is on HD:
`/dev/sdb1 on /mnt/data type ext4 (rw,noatime)
`
Time is correct too.

2. Yes i start markad during recording to have marks if i watch an actual recording series and i want to have marks aldeady then

Ok i set log to verbose in the plugin

**Comment by MegaV0lt** [comment] 2024-07-23 14:39
Som log from syslog:
```
Jul 22 22:10:00 vdr01 vdr: [1562] timer 2 (2 2210-0009 'The Good Neighbor - Das Böse wohnt nebenan') start
Jul 22 22:10:00 vdr01 vdr: [1562] Title: 'The Good Neighbor - Das Böse wohnt nebenan' Subtitle: 'The Good Neighbor'
Jul 22 22:10:00 vdr01 vdr: [1562] markad: cStatusMarkAd::Recording():  recording: The Good Neighbor - Das Böse wohnt nebenan, file name: /video/The_Good_Neighbor_-_Das_Böse_wohnt_nebenan/2024-07-22.22.10.2-0.rec, started, recording count now 1
Jul 22 22:10:00 vdr01 vdr: [1562] markad: cStatusMarkAd::GetEventID(): recording: The Good Neighbor - Das Böse wohnt nebenan, device: STV090x Multistandard, search for timer
Jul 22 22:10:00 vdr01 vdr: [1562] markad: cStatusMarkAd::GetEventID(): timer recording: The Good Neighbor - Das Böse wohnt nebenan
Jul 22 22:10:00 vdr01 vdr: [1562] markad: cStatusMarkAd::GetEventID(): recording: The Good Neighbor - Das Böse wohnt nebenan, timer title: The Good Neighbor - Das Böse wohnt nebenan, channelID: S19.2E-1-1011-11110
Jul 22 22:10:00 vdr01 vdr: [1562] markad: cStatusMarkAd::GetEventID(): recording: The Good Neighbor - Das Böse wohnt nebenan, timer start: Mon Jul 22 22:10:00 2024
Jul 22 22:10:00 vdr01 vdr: [1562] markad: cStatusMarkAd::GetEventID(): recording: The Good Neighbor - Das Böse wohnt nebenan, timer stop:  Tue Jul 23 00:09:00 2024
Jul 22 22:10:00 vdr01 vdr: [1562] markad: cStatusMarkAd::GetEventID(): recording: The Good Neighbor - Das Böse wohnt nebenan, event title: The Good Neighbor - Das Böse wohnt nebenan, channelID: S19.2E-1-1011-11110
Jul 22 22:10:00 vdr01 vdr: [1562] markad: cStatusMarkAd::GetEventID(): recording: The Good Neighbor - Das Böse wohnt nebenan, event eventID: 8912886, eventNextID: 0
Jul 22 22:10:00 vdr01 vdr: [1562] markad: cStatusMarkAd::GetEventID(): recording: The Good Neighbor - Das Böse wohnt nebenan, event start: Mon Jul 22 22:15:00 2024
Jul 22 22:10:00 vdr01 vdr: [1562] markad: cStatusMarkAd::GetEventID(): recording: The Good Neighbor - Das Böse wohnt nebenan, event stop:  Mon Jul 22 23:50:00 2024
Jul 22 22:10:00 vdr01 vdr: [1619] SVDRP vdr01 < 127.0.0.1:56724 message 'Aufnahme:  The Good Neighbor - Das Böse wohnt nebenan'
Jul 22 22:10:00 vdr01 yaVDR: [6717] vdr_rec_msg.sh: Aufnahme:  The Good Neighbor - Das Böse wohnt nebenan
Jul 22 22:10:02 vdr01 vdr: epg2vdr: Recording of 'The Good Neighbor - Das Böse wohnt nebenan' has 'started' [/video/The_Good_Neighbor_-_Das_Böse_wohnt_nebenan/2024-07-22.22.10.2-0.rec]
Jul 22 22:10:02 vdr01 vdr: [1562] info: Aufnahme:  The Good Neighbor - Das Böse wohnt nebenan
Jul 22 22:10:02 vdr01 vdr: epg2vdr: Info: Recording 'The Good Neighbor - Das Böse wohnt nebenan' with doneid -1 added to running list
Jul 22 22:10:50 vdr01 epgd: Found new recording 'The Good Neighbor - Das Böse wohnt nebenan'/'The Good Neighbor'
...
Jul 23 00:09:00 vdr01 vdr: [1562] timer 2 (2 2210-0009 'The Good Neighbor - Das Böse wohnt nebenan') finished with 1 error
Jul 23 00:09:01 vdr01 vdr: [1562] timer 2 (2 2210-0009 'The Good Neighbor - Das Böse wohnt nebenan') stop
Jul 23 00:09:01 vdr01 vdr: [1562] timer 2 (2 2210-0009 'The Good Neighbor - Das Böse wohnt nebenan') set to no event
Jul 23 00:09:01 vdr01 vdr: [1562] deleting timer 2 (2 2210-0009 'The Good Neighbor - Das Böse wohnt nebenan')
Jul 23 00:09:01 vdr01 vdr: epg2vdr: Info: Finished (4223) 'The Good Neighbor - Das Böse wohnt nebenan'; recorded 100%; VPS No
Jul 23 00:09:01 vdr01 vdr: epg2vdr: Info: Recording 'The Good Neighbor - Das Böse wohnt nebenan' finished -  complete (100%)

```

**Comment by kfb77** [comment] 2024-07-23 14:48
> 1. have moved the recording to ext hd in the meantime to watch it out of house

OK, we will need a new recording to check this. But I use the timestamp of the recording directory self, not the content: 
"ls -l /mnt/data/video/The_Good_Neighbor*". Please check this with a recording which was not moved.

All log files tells 22:10 but I get 22:15 as creation time. ext4 is OK, I use it too.

**Comment by MegaV0lt** [comment] 2024-07-23 15:11
I set a new timer at 19:20 Wetter on ZDF HD
Tomorrow i will give an update witth all files and logs

**Comment by kfb77** [comment] 2024-07-23 15:16
> ps: i have markad running during the recording, because i sometime watch during recording and i want marks then...

If you use "during recording" you can not use VPS. This will reduce quality of marks with ÖR, they have usually no logo interruption between broadcast.

> I set a new timer at 19:20 Wetter on ZDF HD

I added this timer too, so we can compare the result. But this very short broadcast will bring new challenges in logo detection.

**Comment by kfb77** [comment] 2024-07-23 15:41
My test timers are finished now, I can not reproduce your problem. There are some useless error logs from index, which I will fix, but no start/end problem.

**Comment by kfb77** [comment] 2024-07-23 18:17
[markad.log](https://github.com/user-attachments/files/16352832/markad.log)
[marks.txt](https://github.com/user-attachments/files/16352840/marks.txt)
No problem with start and end mark. Logo was not detected, because of new logo without "HD". Will be fixed in next version.

**Comment by kfb77** [comment] 2024-07-29 18:37
This issue has been closed because there has been no response
to our request for more information from the original author. With only the
information that is currently in the issue, we don't have enough information
to take action.

**Closed as completed by kfb77** 2024-07-29 18:37 UTC
