### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by Jen200** [kfb77/vdr-plugin-markad#6] opened 2021-09-02 20:44 UTC
I have found a crash in markad.

The output of `markad nice -R --loglevel=4 <dirname>` is [markad.log](https://github.com/kfb77/vdr-plugin-markad/files/7101656/markad.log)

vlc is able to play this video file.

**Comment by kfb77** [comment] 2021-09-03 06:34
I can reproduce this crash with a random recording after deleteting the VDR info file.
There is something wrong with this recording, but this should not result in a crash.

Some questions:
Thu Sep  2 22:33:52 [628028] ERROR: failed loading info - logo detection and pre-/post-timer disabled
Were is the VDR info file from this recording ? Without this you will never get valid marks.

Thu Sep  2 22:33:52 [628028] DEBUG: cDecoder::GetNextPacket(): last frame of filenumber 1 is (5616), end time 224640ms (  3:44min)
Why is the first ts file only 3:44min ? Was this recording interupted ?

**Comment by kfb77** [comment] 2021-09-03 08:26
Crash fixed in this [commit](https://github.com/kfb77/vdr-plugin-markad/commit/63506241eec349ec44c4467a36bf468e47fe3094).
Please test with branch V03.
But as mentioned, marks will not be valid without VDR info file. You have to find the reason and fix it.

**Comment by Jen200** [comment] 2021-09-03 22:19
> Thu Sep 2 22:33:52 [628028] ERROR: failed loading info - logo detection and pre-/post-timer disabled
> Were is the VDR info file from this recording ? Without this you will never get valid marks.

The recording is broken, info file is missing, but ts files looks good.
Thanks for the information about the info file. Does it mean that markad does not work well for old recordings? Does values like 'blackscreenRange' change over time?

> Why is the first ts file only 3:44min ? Was this recording interrupted ?

Yes, but only for 1 or 2 seconds.

> Please test with branch V03.

Tested, work well. Thanks!

**Comment by kfb77** [comment] 2021-09-04 06:19
> Does it mean that markad does not work well for old recordings?

How old is "old" ?
The recording should be TS files (not the old .vdr files) and I need a info file. 

> Does values like 'blackscreenRange' change over time?

Sometimes, If I found a recording that shows me a false positive.

> Tested, work well. Thanks!

I close this issue, more infos if needed in the forum.

**Closed as completed** 2021-09-04 06:20 UTC
Labels: bug
