### ISSUE TITLE
segmentation fault after "duplicate mark on position 31824 type 0xE2 and type 0xe2"

### ISSUE THREAD

**Issue by Jen200** [kfb77/vdr-plugin-markad#3] opened 2021-05-28 17:41 UTC
I have used markad from command line to create marks files for many recordings - it worked well.
But for one recording it crashes.

The output of `markad nice -R --loglevel=4 <dirname>` is [markad.log](https://github.com/kfb77/vdr-plugin-markad/files/6562424/markad.log)

vlc is able to play this video file. The bug is not urgent but maybe good to know.

**Comment by kfb77** [comment] 2021-05-28 19:12
Thanks for your report, segfaults are never a valid behavior. Please keep this recording, maybe I need to download it.

**Comment by kfb77** [comment] 2021-05-28 19:36
Something went totaly wrong with this recording. This log entries make no sense:
Fri May 28 18:58:41 [681568] DEBUG: cMarkAdStandalone::ProcessMark2ndPass(): process overlap detection between frame (75611) at 0:50:24.12 and frame (83123) at 0:55:24.24
Fri May 28 18:58:41 [681568] DEBUG: cMarkAdStandalone::ProcessMark2ndPass(): found overlap from ( 31824) at 0:21:12.25 to ( 62868) at 0:41:54.19 are identical with
Fri May 28 18:58:41 [681568] DEBUG: cMarkAdStandalone::ProcessMark2ndPass():                    ( 75623) at 0:50:24.24 to ( 42048) at 0:28:01.24
Can you make a tar of the recording directory and provide me a download link as PM on https://www.vdr-portal.de/ for user kfb77 ?
`

**Comment by kfb77** [comment] 2021-05-28 20:39
Crash fixed in https://github.com/kfb77/vdr-plugin-markad/tree/jen200, please verify.
But the underlaying problem still exists. I assume it is caused by this error in the recording:
Fri May 28 18:58:41 [681568] DEBUG: AVlog(): skipped MB in I-frame at 6 6
Fri May 28 18:58:41 [681568] DEBUG: AVlog(): Warning MVs not available
Fri May 28 18:58:41 [681568] DEBUG: cDecoder::DecodePacket(): decoding of frame (62724) from stream 0 failed:  decode_error_flags 4

**Comment by kfb77** [comment] 2021-05-28 21:05
Maybe I can catch it without the recording.
Please post a log file with the code from  https://github.com/kfb77/vdr-plugin-markad/tree/jen200

**Comment by Jen200** [comment] 2021-05-29 10:04
The crash is fixed. Thanks!
But the marks files looks strange:

0:05:41.08 (   8532)* detected end of black screen (8532)*
0:21:12.25 (  31824)  moved stop mark (31824) before logo stop mark (62868) at 0:41:54.19, overlap detected
0:21:13.24 (  31848)  detected logo stop (31848)
0:26:29.20 (  39744)* detected logo start (39744)*
0:28:01.24 (  42048)* moved start mark (42048) before logo start mark (75623) at 0:50:24.24, overlap detected*
1:01:23.13 (  92087)  moved stop mark (92087) after logo stop mark (91823) at 1:01:12.24, closing credits detected

[markad.log.zip](https://github.com/kfb77/vdr-plugin-markad/files/6564433/markad.log.zip)

**Comment by kfb77** [comment] 2021-05-29 12:52
I expected this, the crash was only the consequential failure of a bug in the overlap detection.
If I can download the recording it will make my job easier.

**Comment by kfb77** [comment] 2021-05-29 15:11
I can see in your logfile the second overlap check ends to early and use old frames from the first overlap check. This only happens in your recording. I have no idee why, but this may never happen. I revised the object allocation and deletion to avoid these. Please test again and post the log file.

**Comment by Jen200** [comment] 2021-05-29 18:30
Now the marks file looks good

0:05:41.08 (   8532)* detected end of black screen (8532)*
0:21:13.24 (  31848)  detected logo stop (31848)
0:26:29.20 (  39744)* detected logo start (39744)*
0:41:54.19 (  62868)  detected logo stop (62868)
0:50:24.24 (  75623)* detected logo start (75623)*
1:01:23.13 (  92087)  moved stop mark (92087) after logo stop mark (91823) at 1:01:12.24, closing credits detected

[markad.log.zip](https://github.com/kfb77/vdr-plugin-markad/files/6565169/markad.log.zip)

**Comment by kfb77** [comment] 2021-05-29 18:58
The log file looks good too. Fixed without bug found, that is strange.
Fix is now with commit https://github.com/kfb77/vdr-plugin-markad/commit/23e0d44489319af3f90100875d25c98186db6f4a integrated in developer branch V03 and goes to master with next release.

**Closed as completed by kfb77** 2021-05-29 18:58 UTC
Labels: bug
